'use strict';
const assert=require('node:assert/strict');
const {archiveRows,jsonArchiveRows,syncProjects}=require('./archive-sync.js');
const browser=require('./project-home.js');
const project={repo:'hwagok-farm',publicUrl:'https://softm.github.io/hwagok-farm/',publicRepoUrl:'https://github.com/softm/hwagok-farm'};
const row={date:'2026-09-23',title:'사용자 원본 HTML 제목',dir:'20260923-test',kind:'아카이브',desc:'원본 설명',url:project.publicUrl+'records/20260923-test/',repoUrl:project.publicRepoUrl+'/tree/main/public/records/20260923-test'};
const canonical=archiveRows([row],project)[0];
assert.equal(canonical.title,row.title);
assert.equal(canonical.date,row.date);
assert.equal(canonical.url,row.url);
assert.equal(canonical.repoUrl,row.repoUrl);
assert.equal(canonical.recordPath,'public/records/'+row.dir);
assert.equal(canonical.dateSource,'archive-canonical');
assert.deepEqual(archiveRows([],project),[]);
const rootRow={...row,repoUrl:project.publicRepoUrl+'/tree/main/records/'+row.dir};
assert.equal(archiveRows([rootRow],project)[0].recordPath,'records/'+row.dir);
const jsonProject={repo:'baksok-public',publicUrl:'https://softm.github.io/baksok-public/',publicRepoUrl:'https://github.com/softm/baksok-public'};
const jsonData={errors:[],records:[{slug:'2025-front-window-design',date:'2025',title:'전면 유리 디자인',category:'디자인',input:'2025_전면유리',files:[{path:'images/a.jpg',size:10},{path:'index.html',size:20},{path:'notes.md',size:30}]}]};
const jsonRow=jsonArchiveRows(jsonData,jsonProject)[0];
assert.equal(jsonRow.date,'2025');
assert.equal(jsonRow.url,jsonProject.publicUrl+'records/2025-front-window-design/');
assert.equal(jsonRow.repoUrl,jsonProject.publicRepoUrl+'/tree/main/records/2025-front-window-design');
assert.equal(jsonRow.recordPath,'records/2025-front-window-design');
assert.equal(jsonRow.count,3);
assert.deepEqual(jsonRow.files,{images:1,videos:0,audio:0,documents:1,archives:0});
assert.throws(()=>jsonArchiveRows({...jsonData,errors:[{error:'failed'}]},jsonProject));
assert.throws(()=>jsonArchiveRows({...jsonData,records:[jsonData.records[0],jsonData.records[0]]},jsonProject));
for(const repoUrl of ['https://github.com/other/repo/tree/main/records/'+row.dir,project.publicRepoUrl+'/tree/main/private/records/'+row.dir,project.publicRepoUrl+'/tree/main/records/other'])assert.throws(()=>archiveRows([{...row,repoUrl}],project));
for(const bad of [{...row,dir:'../bad'},{...row,title:''},{...row,date:'2026-02-30'},{...row,url:'https://private.vercel.app/'},{...row,repoUrl:project.publicRepoUrl}])assert.throws(()=>archiveRows([bad],project));
assert.throws(()=>archiveRows([row,row],project));
assert.throws(()=>archiveRows({},project));
assert.throws(()=>archiveRows([row],{...project,publicUrl:'https://private.vercel.app/'}));
const meta={entries:{[browser.keyFor(row.url)]:{authoredAt:'2026-10-05',userTitle:'OLD TITLE'}}};
const shown=browser.lists({...project,links:[canonical],chatMetadata:{[browser.keyFor(row.url)]:{userTitle:'OTHER OLD TITLE'}}},meta).public[0];
assert.equal(shown.displayName,row.title);
assert.equal(shown.displayTitle,row.title);
assert.equal(shown.displayDate,row.date);
const card=browser.card(browser.record(project,shown,0,'public'),'cards');
assert.ok(card.includes('datetime="'+row.date+'"'));
assert.ok(card.includes(row.repoUrl));
assert.ok(!card.includes('OLD TITLE'));
assert.ok(!card.includes('작성일 미확인'));
let calls=[];
global.DOMParser=class{parseFromString(markup){return{querySelector(selector){assert.equal(selector,'script#archive-data[type="application/json"]');return {textContent:markup}}}}};
const privateLink={visibility:'private',url:'https://private.vercel.app/secret/',label:'Private link'};
function input(){return {...project,links:[{visibility:'public',url:project.publicUrl+'old/',label:'STALE'},privateLink]}}
async function run(){
 global.fetch=async(url,options)=>{calls.push({url,options});return {ok:true,text:async()=>JSON.stringify([row])}};
 let p=input();await syncProjects([p]);
 assert.equal(p.archiveSync.status,'ok');assert.equal(p.homePublicListCount,1);
 assert.deepEqual(p.links.map(x=>x.url),[row.url,privateLink.url]);
 assert.equal(calls.length,1);assert.equal(calls[0].options.cache,'no-store');
 assert.equal(calls[0].options.credentials,'omit');assert.equal(calls[0].options.redirect,'error');
 assert.ok(calls[0].url.startsWith(project.publicUrl+'?archive-sync='));
 global.fetch=async()=>({ok:false,status:503});p=input();await syncProjects([p]);
 assert.equal(p.archiveSync.status,'error');assert.equal(p.homePublicListCount,null);
 assert.deepEqual(p.links,[privateLink]);
 global.fetch=async()=>({ok:true,text:async()=>'[]'});p=input();await syncProjects([p]);
 assert.equal(p.archiveSync.status,'ok');assert.equal(p.homePublicListCount,0);assert.deepEqual(p.links,[privateLink]);
 global.fetch=async()=>({ok:true,text:async()=>JSON.stringify(jsonData)});
 p={...jsonProject,publicIndexSource:{url:jsonProject.publicUrl+'records/index.json',format:'json-record-index'},links:[privateLink]};await syncProjects([p]);
 assert.equal(p.archiveSync.status,'ok');assert.equal(p.homePublicListCount,1);
 assert.deepEqual(p.links.map(x=>x.url),[jsonRow.url,privateLink.url]);
 calls=[];global.fetch=async()=>{calls.push('UNEXPECTED');throw new Error('Unexpected request')};
 p={...input(),publicIndexSource:{url:'https://private.vercel.app/',format:'html-archive-data'}};await syncProjects([p]);
 assert.equal(p.archiveSync.status,'error');assert.equal(calls.length,0);
 await syncProjects([{repo:'mine-private',privateUrl:privateLink.url,links:[privateLink]}]);
 assert.equal(calls.length,0);
 console.log('PASS: canonical title/date/link parity, snapshot replacement, empty archives, error states, URL validation, private-origin isolation');
}
run().catch(e=>{console.error(e);process.exitCode=1});
