'use strict';
const assert=require('node:assert/strict');
const b=require('./project-home.js');
assert.equal(b.dateOf('2026-09-22 관리기'),'2026-09-22');
assert.equal(b.dateOf('제목','https://example.com/records/20260905-radish/'),'2026-09-05');
assert.equal(b.dateOf('2026-02-30'),null);
assert.equal(b.dateOf('날짜 없음'),null);
assert.equal(b.titleOf('2026-08-11 박 수확 · 사진 53장'),'박 수확');
assert.equal(b.safe('javascript:alert(1)'),'');
assert.equal(b.safe('https://user:secret@example.com'),'');
const rows=[{title:'나',date:null,count:null,index:0},{title:'다',date:'2026-09-30',count:0,index:1},{title:'가',date:'2026-07-05',count:3,index:2},{title:'라',date:'2026-09-30',count:7,index:3}];
assert.deepEqual(b.sortRows(rows,'newest').map(x=>x.title),['다','라','가','나']);
assert.deepEqual(b.sortRows(rows,'oldest').map(x=>x.title),['가','다','라','나']);
assert.deepEqual(b.sortRows(rows,'count-desc').map(x=>x.title),['라','가','다','나']);
assert.deepEqual(b.sortRows(rows,'title-asc').map(x=>x.title),['가','나','다','라']);
assert.deepEqual(b.sortRows(rows,'title-desc').map(x=>x.title),['라','다','나','가']);
assert.deepEqual(rows.map(x=>x.title),['나','다','가','라']);
assert.equal(b.unique([{url:'https://example.com/a/'},{url:'https://example.com/a/index.html'}]).length,1);
const publicLinks=Object.keys(b.FARM).map(slug=>({label:slug,url:'https://softm.github.io/hwagok-farm/'+slug+'/',visibility:'public'}));
const p={repo:'hwagok-farm',category:'농업',privateUrl:'https://hwagok-farm-private.vercel.app/',publicUrl:'https://softm.github.io/hwagok-farm/',links:[...publicLinks,{label:'비공개 샘플',url:'https://hwagok-farm-private.vercel.app/sample/',visibility:'private'}]};
const r=b.lists(p);
assert.equal(r.public.length,publicLinks.length);assert.equal(r.private.length,1);
const privateRecord=b.record(p,{label:'비공개',summary:'DO NOT EXPOSE',url:p.privateUrl},0,'private');
assert.equal(privateRecord.summary,'');assert.equal(privateRecord.count,null);
assert.equal(b.canEnrich(privateRecord,p),false);
assert.equal(b.canEnrich({...privateRecord,visibility:'public'},p),false);
assert.equal(b.canEnrich(b.record(p,r.public[0],0,'public'),p),true);
assert.equal(b.canEnrich({visibility:'public',url:'https://softm.github.io/hwagok-farm-other/x/'},p),false);
const entry=b.record(p,{label:'관수 기록',url:p.publicUrl+'irrigation-20260905/'},0,'public');
assert.equal(b.matches(entry,{q:'스프링클러 2시간',category:'',visibility:''}),true);
assert.equal(b.matches(entry,{q:'',category:'관수',visibility:'private'}),false);
assert.equal(b.homeUrl({repo:'mine-private'}),'https://softm.github.io/projects/mine/');
assert.equal(b.homeUrl({repo:'baksok-public'}),'https://softm.github.io/projects/baksok/');
console.log('PASS: date, five sort orders, unknown-last, immutable sorting, summaries, filters, route preservation, URL safety, private-preview prevention');

assert.equal(b.authoredDate({label:'2026-09-22 작업',url:'https://example.com/20260922/'}),'');
assert.equal(b.authoredDate({date:'2026-09-22'}),'');
assert.equal(b.authoredDate({authoredAt:'2026-09-29T23:30:00Z'}),'2026-09-30');
assert.equal(b.display({authoredAt:'2026-09-30',userTitle:'2026-09-23 현장기록'}).displayName,'2026-09-23 현장기록');
assert.equal(b.display({authoredAt:'2026-09-30',userTitle:'2026-09-30 지정 제목'}).displayName,'지정 제목');
const customized=b.lists(p,{entries:{[b.keyFor(r.public[0].url)]:{authoredAt:'2026-09-30',userTitle:'사용자 제목'}}});
assert.equal(customized.public[0].displayName,'사용자 제목');
assert.equal(customized.public[0].displayDate,'2026-09-30');
console.log('PASS: concurrent authored-date and user-title policy preserved; no filename/event/deployment-date inference');

const baksokReset=b.lists({repo:'baksok-public',category:'음식점',deploymentStatus:'deployed',links:[{label:'새 기록',url:'https://softm.github.io/baksok-public/records/new/',visibility:'public'}]});
assert.equal(baksokReset.public.length,1);
assert.equal(baksokReset.private.length,0);
assert.equal(baksokReset.public[0].displayName,'새 기록');
console.log('PASS: reset-safe baksok list uses only projects.json declared records');
