/* Public project browser. Private origins are links only, never fetched or previewed. */
(function () {
'use strict';
const BASE='https://softm.github.io/projects/';
const VERSION='20261008-inbox-list-title-v22';
const ROUTES={"hwagok-farm":[],"mine-private":[["진료 경과 정리","archive/20260806-right-index-laceration/"],["진료의뢰서 정리","archive/20260810-medical-referral/"],["농업인 안전보험 가입 정리","archive/20260812-farmer-safety-insurance/"],["내가 가진 것 정리","archive/20260819-all-i-have/"],["건강검진·보험 서류 정리","archive/20260903-health-checkup-insurance/"],["임대차 갱신 정리","archive/20260904-onsu-hill-renewal/"]],"onsuhill-private":[["임대차 갱신계약 정리","api/site?route=renewal"],["계약서·생성 문서 목록","api/site?route=documents"],["문자·전화 대응 정리","api/site?route=messages"],["시설 수선 검토","api/site?route=facilities"],["전세계약 갱신 검토","api/site?route=okgil"],["LED 수리 기록·증빙","api/site?route=led-repair"]],"hwagok-land-permit-private":[["사건 접수·증거 정리","case/appeal"],["사건 검토 기록","case/prosecution-outlook"],["처분·항고 정리","case/nonprosecution-appeal"],["사건·대화 타임라인","asset/archive-20260926.html"],["항고장 보관 기록","asset/appeals-20260922/staging.html"]],"baksok-public":[],"ungdo-private":[]};
/* Summaries transcribed from softm/hwagok-farm archive/records.ts.
   Source-reported photo counts are deliberately NOT treated as uploaded files. */
const FARM={
 'farm-machine-rental-20260924':['농기계','북부 임대사업소에서 아세아 관리기를 출고하고 운송·하차한 작업 기록.',['아세아 관리기','임대·운반']],
 'deodeok-harvest-20260923':['수확·채종','더덕 뿌리를 굴취하고 열매(삭과)를 채취한 작업 기록.',['더덕 수확','씨앗 채취']],
 'cultivator-manual-start-20260922':['농기계','관리기 수동시동과 초크 조작을 정리한 기록.',['수동시동','초크']],
 'asea-engine-stop-20260922':['농기계','관리기 엔진을 정지하는 조작 절차를 정리한 기록.',['엔진정지']],
 'fan-gearbox-repair-20260914':['시설·수리','타이거킹 TKF-30 S,P의 좌우 회전 기어박스 파손 확인과 교체 부품 주문.',['30인치 · 310W','기어박스 교체']],
 'mowing-20260907':['벌초','08:30부터 17:00까지 진행한 벌초·풀베기 작업.',['08:30–17:00']],
 'irrigation-20260905':['관수','화이트클로버 파종 후 타이머·스프링클러를 설치한 자동급수 기록.',['2시간 간격','1회 1분']],
 'perilla-transplant-20260830':['재배','들깨 모종 3판 정식과 재배 구획 표시 기록.',['모종 3판','구획 표시']],
 'mowing-20260826':['벌초','07:00부터 14:00까지 진행한 벌초 작업과 작업비 정리.',['07:00–14:00','작업비 35만원']],
 'cctv-internet-20260821':['시설·통신','농막·하우스 CCTV를 연결하기 위한 인터넷 구성 검토.',['핫스팟','Extender N3','Tapo']],
 'sprinkler-thread-20260820':['관수','스프링클러 배관 연결에 필요한 나사 규격 비교.',['1/2인치','3/4인치']],
 'spray-record-20260813':['방제','농막 아랫밭에서 오전 7시에 진행한 방제 작업.',['20L × 2통']],
 'dangol-spray-20260811':['방제','들깨밭에 단골을 살포한 작업 기록.',['20L × 2통']],
 '20260811-gourd-harvest':['수확·채종','화곡농장에서 박 약 50통을 수확한 작업 기록.',['박 약 50통']],
 'onion-purchase-20260811':['구매·보관','양파 구입 내역과 저온창고 보관 기록.',['구매비 453,000원','저온 보관']],
 'onion-sourcing-20260810':['구매·보관','서산 지역 양파 구매처와 구매 물량을 검토한 기록.',['15kg × 30망','총 450kg']],
 'shade-net-20260807':['시설·수리','6평 농막의 쉐이드네트 설치 범위와 크기 검토.',['긴 면 약 7.3m','세로 1.8–1.9m']],
 'freezer-electric-20260711':['시설·전기','냉동고 전기 증설에 필요한 전선과 차단기 구성.',['10SQ · 20m','누전차단기 40A']],
 'farm-awning-repair-20260711':['시설·수리','농막 차양막의 대각선 보강과 시정조치 기록.',['대각선 보강','전후 비교']],
 'fertilizer-plan':['재배','들깨·열무 재배를 위한 4개 필지의 밑거름 시비 계획.',['4개 필지','맞춤18호']],
 'moskill-20260527':['방제','박밭 3개 두둑에 진행한 모스킬 잎벌레 방제 기록.',['3개 두둑','약 50L']],
 'white-clover':['재배','화이트클로버 종자와 황토 배합, 파종 구역을 정리한 계획.',['종자 1kg','황토 배합']],
 'farm-machine-rental':['농기계','서산 북부분소 농기계 임대·운반 이용 절차와 준비서류.',['이용 절차','준비서류']]
};
const VIEWS=[['cards','카드형'],['list','목록형'],['table','표형'],['gallery','갤러리형']];
const SORTS=['newest','oldest','title-asc','title-desc','count-desc'];
const collator=new Intl.Collator('ko',{numeric:true,sensitivity:'base'});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safe(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch{return ''}}
function homeUrl(p){const slug=({'baksok-public':'baksok','mine-private':'mine'}[p.repo]||String(p.repo||'').replace(/-private$/,''));return /^[a-zA-Z0-9_-]+$/.test(slug)?BASE+slug+'/':''}
function button(url,label,kind=''){const u=safe(url);return u?`<a class="button ${esc(kind)}" href="${esc(u)}" rel="noreferrer">${esc(label)}</a>`:''}
function unique(rows){const out=[],seen=new Map();for(const row of rows){const key=keyFor(row.url)||row.label;if(!seen.has(key)){seen.set(key,out.length);out.push({...row});continue}const target=out[seen.get(key)];for(const [k,v] of Object.entries(row))if(v!==undefined&&v!==null&&v!=='')target[k]=v}return out}
const text=v=>typeof v==='string'?v.trim():'';
function keyFor(value){const s=safe(value);if(!s)return '';const u=new URL(s);u.hash='';u.pathname=u.pathname.replace(/\/index\.html$/i,'/').replace(/\/+$/,'')||'/';return u.href.replace(/\/$/,'')}
function dateOnly(value){const s=text(value),m=s.match(/^(\d{4})-?(\d{2})-?(\d{2})(.*)$/);if(!m)return '';const y=Number(m[1]),mo=Number(m[2]),d=Number(m[3]);if(y<1000||mo<1||mo>12||d<1||d>new Date(Date.UTC(y,mo,0)).getUTCDate())return '';const day=`${m[1]}-${m[2]}-${m[3]}`;if(!m[4])return day;if(!/^T\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?(?:Z|[+-]\d{2}:\d{2})$/.test(m[4]))return '';const timestamp=new Date(day+m[4]);if(!Number.isFinite(timestamp.getTime()))return '';const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(timestamp);const get=type=>parts.find(p=>p.type===type).value;return `${get('year')}-${get('month')}-${get('day')}`}
function authoredDate(row){if(row.dateSource==='archive-canonical')return dateOnly(row.date);for(const name of ['authoredAt','chatCreatedAt','writtenAt','authoredDate']){const d=dateOnly(row[name]);if(d)return d}if(['chat-created','chat-written','user-specified','conversation-created-at','project-conversation-created-at'].includes(row.dateSource)||row.dateType==='authored')return dateOnly(row.createdAt)||dateOnly(row.date);return ''}
function leadingDate(title){const m=title.match(/^(\d{4}-?\d{2}-?\d{2})(?:[\s_·:]+)(.+)$/);return m&&dateOnly(m[1])?{date:dateOnly(m[1]),rest:m[2]}:null}
function display(row){const date=authoredDate(row);if(typeof row.listTitle==='string'&&row.listTitle.length){const title=row.listTitle;return {...row,displayDate:date,displayName:title,displayTitle:title,titleSource:row.titleSource||'inbox-name'}}if(row.dateSource==='archive-canonical'){const title=text(row.title)||text(row.label)||'기록';return {...row,displayDate:date,displayName:title,displayTitle:title,titleSource:'archive-canonical'}}const manual=text(row.userTitle)||text(row.customTitle)||(row.titleSource==='user'?(text(row.title)||text(row.label)):'');let title=manual||text(row.chatTitle)||text(row.originalChatTitle)||text(row.title)||text(row.label)||'채팅 정리';const prefix=leadingDate(title);if(prefix&&(!manual||prefix.date===date))title=prefix.rest;return {...row,displayDate:date,displayName:title,displayTitle:(date||'작성일 미확인')+' '+title,titleSource:manual?'user':row.titleSource||'existing'}}
function labelRows(rows,p,metadata){return rows.map(row=>{const key=keyFor(row.url);return row.dateSource==='archive-canonical'?display(row):display({...metadata?.entries?.[key],...row,...p.chatMetadata?.[key]})})}
function lists(p,metadata={}){
 const links=Array.isArray(p.links)?p.links:[],pub=links.filter(x=>x.visibility==='public'),base=safe(p.privateUrl);
 const declaredPrivate=links.filter(x=>x.visibility==='private');
 // projects.json is the canonical source for private routes. Hard-coded ROUTES are legacy fallback only.
 let pri=declaredPrivate.length?declaredPrivate:(ROUTES[p.repo]||[]).map(([label,path])=>({label,url:base?base.replace(/\/$/,'')+'/'+path:'',visibility:'private'}));
 pri=unique(pri);
 if(!pri.length&&base&&['deployed','static-html-deployed','authenticated-github-live'].includes(p.deploymentStatus))pri.push({label:'기존 비공개 채팅 정리',url:base,visibility:'private',note:p.authProvider==='chatgpt-legacy'?'ChatGPT Sites 인증 경로 · Vercel 전환 전':'개별 채팅 목록 연결 확인 필요'});
 if(p.repo==='yeonseo'&&!pri.length)pri.push({label:'비공개 기록',url:'',visibility:'private',note:'비공개 저장소 보관 · 웹 연결 전'});
 if(p.repo==='medical-finder'&&!pri.length)pri.push({label:'사이트 기획·데이터·구현 문서',url:'',visibility:'private',note:'비공개 저장소 보관 · 웹 연결 전'});
 return {public:labelRows(unique(pub),p,metadata),private:labelRows(pri,p,metadata)};
}
function dateOf(...values){for(const value of values){const m=String(value||'').match(/(?:^|[^0-9])(20\d{2})[-_.]?(\d{2})[-_.]?(\d{2})(?!\d)/);if(!m)continue;const d=`${m[1]}-${m[2]}-${m[3]}`,n=Date.parse(d+'T00:00:00Z');if(Number.isFinite(n)&&new Date(n).toISOString().slice(0,10)===d)return d}return null}
function titleOf(label){return String(label||'기록').replace(/^20\d{2}[-_.]?\d{2}[-_.]?\d{2}\s*/,'').replace(/\s*[·|]\s*사진\s*\d+장\s*$/,'').trim()}
function sortRows(rows,sort){return rows.slice().sort((a,b)=>{let n=0;if(sort==='newest'||sort==='oldest'){if(!a.date||!b.date){if(Boolean(a.date)!==Boolean(b.date))return a.date?-1:1}else n=a.date.localeCompare(b.date)*(sort==='newest'?-1:1)}else if(sort==='count-desc'){const ak=Number.isFinite(a.count),bk=Number.isFinite(b.count);if(ak!==bk)return ak?-1:1;if(ak)n=b.count-a.count}else n=collator.compare(a.displayName||a.title,b.displayName||b.title)*(sort==='title-desc'?-1:1);return n||collator.compare(a.displayName||a.title,b.displayName||b.title)||(a.index-b.index)})}
function record(p,x,index,visibility){let slug='';try{slug=new URL(x.url).pathname.replace(/\/$/,'').split('/').pop()}catch{}
 const known=p.repo==='hwagok-farm'&&visibility==='public'&&x.dateSource!=='archive-canonical'?FARM[slug]:null;
 const shown=x.displayName?x:display(x);const repoName=visibility==='private'?(p.privateRepo||p.repo):(p.publicRepo||p.repo);const repoUrl=x.repoUrl||(visibility==='private'?(p.privateRepoUrl||''):(p.publicRepoUrl||''));const recordPath=text(x.recordPath);const recordDir=text(x.directory)||text(x.recordDir)||recordPath.replace(/^.*\//,'')||slug;return {...shown,index,visibility,title:shown.displayTitle,date:shown.displayDate||null,category:known?.[0]||x.category||p.category||'기록',summary:visibility==='private'?(x.publicSummary||''):(known?.[1]||x.summary||x.description||''),tags:known?.[2]||[],count:null,files:null,thumbnail:'',directory:false,recordDir,recordPath,repoName,repoUrl};
}
function repoLinks(p){const pubName=p.publicRepo||p.repo,priName=p.privateRepo;return button(p.repoStatus==='missing'?'':p.publicRepoUrl,pubName?'GitHub · '+pubName:'공개 저장소','repo-link')+button(p.privateRepoUrl,priName?'GitHub · '+priName:'비공개 저장소','repo-link')}
function sourceLinks(x){if(x.directory&&x.project)return repoLinks(x.project);if(x.directory)return button(x.repoUrl,x.repoName?'GitHub · '+x.repoName:'GitHub 저장소','repo-link');if(!x.recordDir)return button(x.repoUrl,x.repoName?'GitHub · '+x.repoName:'GitHub 저장소','repo-link');let dirUrl='',rootUrl='';if(x.repoUrl){try{const u=new URL(x.repoUrl);if(u.hostname==='github.com'){const parts=u.pathname.split('/').filter(Boolean);if(parts.length>=2){rootUrl=u.origin+'/'+parts[0]+'/'+parts[1];dirUrl=parts.length>2?u.href.replace(/\/$/,''):rootUrl+'/tree/main/'+String(x.recordPath||('public/records/'+x.recordDir)).replace(/^\/+/, '')}}}catch{}}return button(rootUrl,x.repoName?'GitHub · '+x.repoName:'GitHub 저장소','repo-link')+'<span class="repo-separator" aria-hidden="true"> › </span>'+button(dirUrl,x.recordDir,'repo-link record-dir-link')}
function status(p){return `<details class="deployment-status"><summary>배포·미디어 점검 상태</summary><p>${esc(p.mediaStatus||'미확인')}</p><p>${esc(p.deploymentNote||'운영 배포 상태 확인 전')}</p></details>`}
function mediaText(x){if(x.directory)return `공개 ${x.publicCount===null?'확인 실패':x.publicCount} · 비공개 ${x.privateCount}`;if(!x.files)return '';const parts=[['images','사진'],['videos','영상'],['audio','음성'],['documents','문서'],['archives','ZIP']].filter(([k])=>x.files[k]>0).map(([k,v])=>`${v} ${x.files[k]}`);return parts.join(' · ')||'첨부 0'}
function mediaHTML(x){const t=mediaText(x);return t?`<span class="file-count" title="${x.directory?'등록된 기록 수':'공개 본문에 연결된 파일 수 · 파일 재생 가능 여부와는 별개'}">${esc(t)}</span>`:''}
function dateHTML(x){return x.date?`<time datetime="${x.date}">${x.date}</time>`:'<span class="undated">작성일 미확인</span>'}
function thumbnail(x){const placeholder=x.visibility==='private'?'비공개 기록':x.category;return `<div class="record-image"><div class="image-placeholder"><span aria-hidden="true">${x.visibility==='private'?'🔒':'▧'}</span><b>${esc(placeholder)}</b></div>${x.visibility!=='private'&&safe(x.thumbnail)?`<img src="${esc(x.thumbnail)}" alt="${esc(x.title)} 관련 사진" loading="lazy" decoding="async" referrerpolicy="no-referrer">`:''}</div>`}
function card(x,view){const action=button(x.url,x.directory?'프로젝트 열기':x.visibility==='private'?'인증 후 열기':'기록 열기','primary');return `<article class="record-card ${x.visibility}" data-record="${esc(x.url||x.label)}" data-authored-date="${esc(x.date||'')}" data-title-source="${esc(x.titleSource||'existing')}">${view==='gallery'?thumbnail(x):''}<div class="record-body"><div class="record-meta">${(x.directory||x.dateSource==='archive-canonical')?dateHTML(x):''}<span>${esc(x.category)}</span>${x.visibility==='private'?'<span class="lock-label">🔒 비공개</span>':''}</div><h3>${safe(x.url)?`<a href="${esc(safe(x.url))}" rel="noreferrer">${esc(x.title)}</a>`:esc(x.title)}</h3>${x.summary?`<p class="record-summary">${esc(x.summary)}</p>`:''}${x.tags.length?`<div class="record-tags">${x.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div>`:''}<div class="record-bottom">${mediaHTML(x)}${x.note?`<span class="record-warning">${esc(x.note)}</span>`:''}${sourceLinks(x)}${action||'<span class="disabled">웹 연결 전</span>'}</div></div></article>`}
function table(rows,state,isDirectory){const active={date:['newest','oldest'],title:['title-asc','title-desc'],count:['count-desc']};function th(key,label){const selected=active[key]?.includes(state.sort),aria=selected?(state.sort==='oldest'||state.sort==='title-asc'?'ascending':'descending'):'none';return `<th scope="col" aria-sort="${aria}"><button type="button" data-sortkey="${key}">${label} <span aria-hidden="true">${selected?(aria==='ascending'?'↑':'↓'):'↕'}</span></button></th>`}return `<div class="record-table-wrap" tabindex="0" role="region" aria-label="${isDirectory?'프로젝트':'기록'} 목록 표. 작은 화면에서는 좌우로 스크롤할 수 있습니다."><table class="record-table"><caption class="sr-only">날짜, 제목, 분류, 자료 수와 연결. 날짜·제목·자료 수 머리글로 정렬할 수 있습니다.</caption><thead><tr>${th('date',isDirectory?'최근 기록':'날짜')}${th('title','제목')}<th scope="col">분류</th>${th('count',isDirectory?'기록 수':'첨부자료')}<th scope="col">열기</th></tr></thead><tbody>${rows.map(x=>`<tr data-record="${esc(x.url||x.label)}" data-authored-date="${esc(x.date||'')}" data-title-source="${esc(x.titleSource||'existing')}"><td>${dateHTML(x)}</td><td><strong>${safe(x.url)?`<a href="${esc(safe(x.url))}" rel="noreferrer">${esc(x.title)}</a>`:esc(x.title)}</strong>${x.visibility==='private'?'<span class="lock-label"> 🔒</span>':''}${x.summary?`<p>${esc(x.summary)}</p>`:''}${x.note?`<small class="record-warning">${esc(x.note)}</small>`:''}</td><td>${esc(x.category)}</td><td>${mediaHTML(x)||'<span class="undated">—</span>'}</td><td><div class="table-links">${sourceLinks(x)}${button(x.url,x.visibility==='private'?'인증 후 열기':'열기')||'<span class="disabled">연결 전</span>'}</div></td></tr>`).join('')}</tbody></table></div>`}
function controls(rows,directory,state){const categories=[...new Set(rows.map(x=>x.category))].sort(collator.compare);const sorts=[['newest','최신순 (기록일)'],['oldest','오래된순 (기록일)'],['title-asc','제목순 (가나다)'],['title-desc','제목순 (역순)'],['count-desc',directory?'기록 많은순':'첨부자료 많은순']];return `<div class="browser-controls"><div class="search-row"><label class="search-field" for="search"><span>검색</span><input id="search" type="search" placeholder="제목·핵심 내용·분류로 검색" autocomplete="off"></label><label for="category"><span>분류</span><select id="category"><option value="">전체 분류</option>${categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select></label>${directory?'':`<label for="visibility"><span>공개 여부</span><select id="visibility"><option value="">전체</option><option value="public">공개</option><option value="private">비공개</option></select></label>`}</div><div class="view-row"><div class="view-switch" role="group" aria-label="보기 방식">${VIEWS.map(([v,label])=>`<button type="button" data-view="${v}" aria-pressed="${state.view===v}">${label}</button>`).join('')}</div><label class="sort-field" for="sort"><span>정렬</span><select id="sort">${sorts.map(([v,label])=>`<option value="${v}" ${state.sort===v?'selected':''}>${label}</option>`).join('')}</select></label><button type="button" class="reset-button" data-reset>검색 초기화</button></div><div class="results-line"><span id="result-count" role="status" aria-live="polite"></span><span id="metadata-status" class="muted"></span></div></div>`}
function searchable(x){return [x.title,x.date,x.category,x.summary,...x.tags,mediaText(x)].join(' ').normalize('NFKC').toLocaleLowerCase()}
function matches(x,state){const terms=state.q.normalize('NFKC').toLocaleLowerCase().split(/\s+/).filter(Boolean);return (!state.category||x.category===state.category)&&(!state.visibility||x.visibility===state.visibility)&&terms.every(t=>searchable(x).includes(t))}
function canEnrich(x,p){if(x.directory||x.visibility!=='public'||!safe(x.url)||!safe(p.publicUrl))return false;const u=new URL(x.url),root=new URL(p.publicUrl);return u.origin===new URL(BASE).origin&&root.origin===u.origin&&u.pathname.startsWith(root.pathname.replace(/\/$/,'')+'/')&&u.pathname!==root.pathname&&!u.pathname.startsWith('/projects/')}
function extractMetadata(text,url){const doc=new DOMParser().parseFromString(text,'text/html');const root=doc.querySelector('main')||doc.body;root.querySelectorAll('script,style,nav,header,footer').forEach(n=>n.remove());const counts={images:0,videos:0,audio:0,documents:0,archives:0};const seen=new Set();let thumb='';for(const node of root.querySelectorAll('img[src],video[src],audio[src],source[src],a[href]')){const raw=node.getAttribute('src')||node.getAttribute('href');let u;try{u=new URL(raw,url)}catch{continue}if(u.protocol!=='https:'||u.origin!==new URL(url).origin||u.username||u.password)continue;const path=u.pathname.toLowerCase();if(/(?:favicon|logo|icon|placeholder)/.test(path))continue;const type=/\.(jpe?g|png|webp|gif|avif)$/.test(path)?'images':/\.(mp4|webm|mov|m4v)$/.test(path)?'videos':/\.(mp3|m4a|wav|ogg|flac|aac)$/.test(path)?'audio':/\.(pdf|md|txt|docx?|xlsx?|pptx?|hwp|hwpx)$/.test(path)?'documents':/\.(zip|7z)$/.test(path)?'archives':null;if(!type)continue;if(type==='images'&&node.tagName==='IMG'&&node.hasAttribute('width')&&Number(node.getAttribute('width'))>0&&Number(node.getAttribute('width'))<80)continue;u.hash='';const key=u.origin+u.pathname;if(seen.has(key))continue;seen.add(key);counts[type]++;if(type==='images'&&!thumb)thumb=u.href}
 const candidates=[...root.querySelectorAll('p')].map(n=>n.textContent.replace(/\s+/g,' ').trim());const summary=candidates.find(t=>t.length>=25&&t.length<=240&&!/로그인|비밀번호|공개 아카이브|기존 상세|미디어.*누락|전체 프로젝트|배포.*확인/.test(t))||'';
 return {files:counts,count:Object.values(counts).reduce((a,b)=>a+b,0),thumbnail:thumb,summary};
}
async function enrich(rows,p,done){const queue=rows.filter(x=>canEnrich(x,p));if(!queue.length)return;const label=document.getElementById('metadata-status');label.textContent='공개 첨부정보 확인 중';let cursor=0;await Promise.all(Array.from({length:Math.min(4,queue.length)},async()=>{while(cursor<queue.length){const x=queue[cursor++],controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(x.url,{credentials:'omit',redirect:'error',signal:controller.signal});if(!response.ok||!(response.headers.get('content-type')||'').includes('text/html'))continue;const text=await response.text();if(text.length>2500000)continue;const m=extractMetadata(text,x.url);x.files=m.files;x.count=m.count;x.thumbnail=m.thumbnail;if(!x.summary)x.summary=m.summary}catch{/* Unknown metadata stays unknown, never counted as zero. */}finally{clearTimeout(timer)}}}));label.textContent='';done()}
function loadState(){let saved={};try{saved=JSON.parse(localStorage.getItem('softm-project-browser')||'{}')||{}}catch{}return {view:VIEWS.some(([v])=>v===saved.view)?saved.view:'cards',sort:SORTS.includes(saved.sort)?saved.sort:'newest',q:'',category:'',visibility:''}}
function saveState(state){try{localStorage.setItem('softm-project-browser',JSON.stringify({view:state.view,sort:state.sort}))}catch{}}
function mount(all,p,metadata={}){const area=document.getElementById('app'),directory=!p,state=loadState();area.removeAttribute('aria-live');let rows;
 if(p){const r=lists(p,metadata);rows=[...r.public.map((x,i)=>record(p,x,i,'public')),...r.private.map((x,i)=>record(p,x,r.public.length+i,'private'))];document.title=p.title+' · 프로젝트 홈';document.getElementById('title').textContent=p.title;document.getElementById('lead').textContent=p.description||'';document.getElementById('back').hidden=false;area.innerHTML=`<div class="project-links"><nav class="tabs" aria-label="기록 목록"><a class="button" href="#public">공개 ${r.public.length}</a><a class="button" href="#private">비공개 ${r.private.length}</a></nav><div class="actions repo">${repoLinks(p)}${button(p.publicUrl,'공개 서비스·기록 홈')}</div></div><p class="access-note">비공개 기록은 해당 사이트에서 인증 후 열립니다. 비공개 본문·사진은 이 목록에 표시하지 않습니다.</p>${controls(rows,false,state)}<div id="results"></div><p class="browser-footnote">첨부 수는 공개 본문에 연결된 사진·영상·음성·문서·ZIP 기준입니다. 파일 열림·재생 보장과는 별개이며, 미확인 수량은 ‘—’로 표시하고 수량 정렬의 뒤에 둡니다. ZIP 아카이브 날짜·제목은 배포된 원본의 canonical 메타데이터를 그대로 사용합니다. 그 외 기록은 확인된 채팅 작성일을 사용하며, 날짜 미확인 항목은 날짜 정렬의 뒤에 둡니다.</p>${status(p)}`}
 else{rows=all.map((project,index)=>{const r=lists(project,metadata),dates=[...r.public,...r.private].map(x=>x.displayDate).filter(Boolean).sort();return {index,directory:true,project,visibility:'public',title:project.title,label:project.title,category:project.category||'프로젝트',summary:project.description||'',url:homeUrl(project),tags:[],date:dates.at(-1)||null,count:project.archiveSync?.status==='error'?null:r.public.length+r.private.length,publicCount:project.archiveSync?.status==='error'?null:r.public.length,privateCount:r.private.length,thumbnail:'',files:null,repoName:project.publicRepo||project.repo,repoUrl:project.publicRepoUrl||''}});document.getElementById('title').textContent='전체 프로젝트';document.getElementById('lead').textContent='프로젝트별 기록과 자료를 찾아보세요.';area.innerHTML=`${controls(rows,true,state)}<div id="results"></div>`}
 const results=document.getElementById('results');
 function render(){const focusKey=document.activeElement?.dataset.sortkey;const visible=sortRows(rows.filter(x=>matches(x,state)),state.sort);document.getElementById('result-count').textContent=`${directory?'프로젝트':'기록'} ${visible.length} / 전체 ${rows.length}`;const groups=directory?[['directory','프로젝트',visible]]:[['public','공개 기록',visible.filter(x=>x.visibility==='public')],['private','비공개 기록',visible.filter(x=>x.visibility==='private')]];results.innerHTML=visible.length?groups.filter(([, ,items])=>items.length).map(([id,title,items])=>`<section id="${id}" class="record-section"><h2>${title} <span class="count">${items.length}개</span></h2>${state.view==='table'?table(items,state,directory):`<div class="record-grid" data-layout="${state.view}">${items.map(x=>card(x,state.view)).join('')}</div>`}</section>`).join(''):'<div class="empty"><p>조건에 맞는 기록이 없습니다.</p><button type="button" class="button" data-reset>검색 초기화</button></div>';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===state.view)));document.getElementById('sort').value=state.sort;results.querySelectorAll('.record-image img').forEach(img=>img.addEventListener('error',()=>img.remove(),{once:true}));if(focusKey)results.querySelector(`[data-sortkey="${focusKey}"]`)?.focus({preventScroll:true});document.documentElement.dataset.rendered=VERSION;document.documentElement.dataset.view=state.view;document.documentElement.dataset.sort=state.sort}
 area.addEventListener('click',event=>{const jump=event.target.closest('.tabs a');if(jump){const mode=jump.getAttribute('href').slice(1);if(['public','private'].includes(mode)){event.preventDefault();state.visibility=mode;document.getElementById('visibility').value=mode;render();document.getElementById(mode)?.scrollIntoView({block:'start'});}return}const b=event.target.closest('button');if(!b)return;if(b.dataset.view){state.view=b.dataset.view;saveState(state);render()}else if(b.dataset.sortkey){const key=b.dataset.sortkey;state.sort=key==='date'?(state.sort==='newest'?'oldest':'newest'):key==='title'?(state.sort==='title-asc'?'title-desc':'title-asc'):'count-desc';saveState(state);render()}else if(b.hasAttribute('data-reset')){state.q='';state.category='';state.visibility='';document.getElementById('search').value='';document.getElementById('category').value='';const v=document.getElementById('visibility');if(v)v.value='';render();document.getElementById('search').focus()}});
 document.getElementById('search').addEventListener('input',e=>{state.q=e.target.value.trim();render()});document.getElementById('category').addEventListener('change',e=>{state.category=e.target.value;render()});document.getElementById('visibility')?.addEventListener('change',e=>{state.visibility=e.target.value;render()});document.getElementById('sort').addEventListener('change',e=>{state.sort=e.target.value;saveState(state);render()});render();if(p)enrich(rows,p,render);
}
async function run(){const area=document.getElementById('app');try{const response=await fetch(BASE+'projects.json?v='+VERSION,{cache:'no-store',credentials:'omit'});if(!response.ok)throw new Error('HTTP '+response.status);const data=await response.json();if(!Array.isArray(data.projects))throw new Error('프로젝트 목록 형식 오류');let metadata={},metadataMissing=false;try{const mr=await fetch(BASE+'chat-metadata.json?v='+VERSION,{cache:'no-store',credentials:'omit'});if(!mr.ok)throw new Error();metadata=await mr.json();if(metadata.schemaVersion!==1||!metadata.entries)throw new Error()}catch{metadata={};metadataMissing=true}const registered=data.projects.slice().sort((a,b)=>(a.order||0)-(b.order||0));const folder=location.pathname.replace(/^\/projects\//,'').split('/')[0].replace(/^index\.html$/,'');const id=document.body.dataset.project||(folder?registered.find(p=>new URL(homeUrl(p)).pathname==='/projects/'+folder+'/')?.repo:null);if(folder&&!id)throw new Error('프로젝트 홈 경로를 찾을 수 없습니다.');const p=id?registered.find(p=>p.repo===id):null;if(id&&!p)throw new Error('등록된 프로젝트를 찾을 수 없습니다.');const deployedStatuses=new Set(['deployed','static-html-deployed','authenticated-github-live']);const visible=registered.filter(x=>deployedStatuses.has(x.deploymentStatus));const archiveTargets=p?[p]:visible;if(archiveTargets.some(x=>x.publicIndexSource||x.repo==='hwagok-farm')){if(!window.SoftmArchiveSync)throw new Error('공개 목록 동기화 모듈을 불러오지 못했습니다.');await window.SoftmArchiveSync.syncProjects(archiveTargets)}mount(p?registered:visible,p,metadata);const syncFailures=archiveTargets.filter(x=>x.archiveSync?.status==='error');if(syncFailures.length)area.insertAdjacentHTML('afterbegin',syncFailures.map(x=>'<p class="empty" role="alert">'+esc(x.title+' · '+x.archiveSync.message)+' '+button(x.publicUrl,'공개 원본 홈 확인')+'</p>').join(''));if(metadataMissing)area.insertAdjacentHTML('afterbegin','<p class="empty">작성일·지정 제목 정보를 불러오지 못했습니다. 날짜를 임의로 채우지 않고 기존 목록을 표시합니다.</p>')}catch(e){area.innerHTML=`<p class="empty">목록을 불러오지 못했습니다. ${esc(e.message)}</p>${button('https://github.com/softm/softm.github.io/blob/main/projects/projects.json','원본 목록 확인')}`}}
if(typeof module!=='undefined'&&module.exports){module.exports={keyFor,dateOnly,authoredDate,display,labelRows,VERSION,homeUrl,lists,safe,unique,dateOf,titleOf,sortRows,record,matches,canEnrich,FARM,card,table};return}
run();
})();
// Retain the small server-side renderer contract used by existing title-policy tests.
if(typeof module!=='undefined'&&module.exports){
 module.exports.records=function(title,items,privateMode){
  const f=module.exports,escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  return '<section><h2>'+escape(title)+'</h2>'+items.map(item=>{const x=f.display(item),u=f.safe(x.url);return '<article><h3>'+(x.displayDate?'<time datetime="'+escape(x.displayDate)+'">'+escape(x.displayDate)+'</time>':'작성일 미확인')+' '+escape(x.displayName)+'</h3>'+(u?'<a href="'+escape(u)+'">'+(privateMode?'인증 후 열기':'기록 열기')+'</a>':'')+'</article>'}).join('')+'</section>';
 };
}

// Actions permissions re-enabled; publish verification trigger 2026-09-30
