/* Public directory only. Authentication and private content stay on the origin servers. */
(function () {
'use strict';
const BASE='https://softm.github.io/projects/';
const VERSION='20260930-project-homes-v3';
const ROUTES={"hwagok-farm":[["농업인 안전보험 가입 기록","records/20260812-nh-farm-safety-insurance/"],["파종 작업 기록","records/20260905-radish-sowing/"],["비료 사용 계획","fertilizer-plan-20260914/"],["방제 상담 기록","pesticide-consultation/"]],"mine-private":[["진료 경과 정리","archive/20260806-right-index-laceration/"],["진료의뢰서 정리","archive/20260810-medical-referral/"],["농업인 안전보험 가입 정리","archive/20260812-farmer-safety-insurance/"],["내가 가진 것 정리","archive/20260819-all-i-have/"],["건강검진·보험 서류 정리","archive/20260903-health-checkup-insurance/"],["임대차 갱신 정리","archive/20260904-onsu-hill-renewal/"]],"father-hospital-treatment-private":[["진료기록 발급·정정 요청","archive/20260923-seosan-medical-record-ha-correction"],["민원답변 검토","archive/20260911-seosan-medical-center-response-review"],["보험 보완서류 준비","archive/20260908-teacher-mutual-aid-adl-documents"],["보험금 심사 관련 민원","archive/20260819-teacher-mutual-aid-insurance-complaint"],["의무기록 정정·민원","archive/20260811-seosan-medical-record-complaint"],["의무기록 정정 및 재심사 정리","archive/20260807-seosan-medical-record-correction"],["진료 녹취 정리","archive/20260703-neuro-ophthalmology-visual-field"]],"onsuhill-private":[["임대차 갱신계약 정리","api/site?route=renewal"],["계약서·생성 문서 목록","api/site?route=documents"],["문자·전화 대응 정리","api/site?route=messages"],["시설 수선 검토","api/site?route=facilities"],["전세계약 갱신 검토","api/site?route=okgil"],["LED 수리 기록·증빙","api/site?route=led-repair"]],"hwagok-land-permit-private":[["사건 접수·증거 정리","case/appeal"],["사건 검토 기록","case/prosecution-outlook"],["처분·항고 정리","case/nonprosecution-appeal"],["사건·대화 타임라인","asset/archive-20260926.html"],["항고장 보관 기록","asset/appeals-20260922/staging.html"]],"baksok-public":[["가구 계약·설비 구매 정리","reports/20260909-furniture-gas/"],["제품 배송·개봉 기록","reports/20260911-rir4000s-delivery/"],["운영·세무 분석 정리","reports/20260721-tax/"]],"ungdo-private":[["토지 관련 종합 기록","ungdo-case"],["현장·방문 기록","ungdo-66-field-record"],["잔여지 검토 기록","40-25-sale"],["원상복구·농지 조성 기록","ungdo-66-restoration-agreement"],["배수시설 관련 기록","ungdo-66-sewer-pipe"],["지도·현장사진 보고서","reports/ungdo-66-20260907/index.html"],["합의·공증 상세 기록","live/records/20260911-notarization/deployed-media-report.html"]]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safe(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch{return ''}}
function homeUrl(p){const slug=({'baksok-public':'baksok','mine-private':'mine'}[p.repo]||String(p.repo||'').replace(/-private$/,''));if(!/^[a-zA-Z0-9_-]+$/.test(slug))return '';return BASE+slug+'/'}
function button(url,label,kind=''){const u=safe(url);return u?`<a class="button ${esc(kind)}" href="${esc(u)}" rel="noreferrer">${esc(label)}</a>`:''}
function unique(rows){const found=new Set();return rows.filter(x=>{const key=safe(x.url).replace(/(?:index\.html)?\/$/,'')||x.label;if(found.has(key))return false;found.add(key);return true})}
function lists(p){
 const links=Array.isArray(p.links)?p.links:[];
 const pub=links.filter(x=>x.visibility==='public');
 const base=safe(p.privateUrl);
 let pri=(ROUTES[p.repo]||[]).map(([label,path])=>({label,url:base?base.replace(/\/$/,'')+'/'+path:'',visibility:'private'}));
 pri=unique(pri.concat(links.filter(x=>x.visibility==='private')));
 if(p.repo==='baksok-public')pub.unshift({label:'가스레인지 교체 검토 기록',url:'https://softm.github.io/baksok-public/20260819_rir4000s_13ea/',visibility:'public'});
 if(!pri.length&&base)pri.push({label:'기존 비공개 채팅 정리',url:base,visibility:'private',note:p.authProvider==='chatgpt-legacy'?'기존 ChatGPT Sites 인증 경로입니다. Vercel 전환은 미완료입니다.':'개별 채팅 목록 연결 상태를 확인해야 합니다.'});
 if(p.repo==='yeonseo')pri.push({label:'사진·영상·음성 기록 모음',url:'',note:'Private GitHub 원본은 보존되어 있습니다. 인증된 웹 배포 연결 전입니다.'});
 if(p.repo==='medical-finder'&&!pri.length)pri.push({label:'사이트 기획·데이터·구현 문서',url:'',note:'비공개 저장소에 보관 중이며 인증된 운영 URL이 아직 없습니다.'});
 return {public:unique(pub),private:pri};
}
function repoLinks(p){return button(p.repoStatus==='missing'?'':p.publicRepoUrl,'GitHub 공개 저장소')+button(p.privateRepoUrl,'🔒 GitHub 비공개 저장소')}
function records(title,items,privateMode){const mode=privateMode?'private':'public';const rows=items.map(x=>{const action=button(x.url,privateMode?'인증 후 채팅 열기':'상세 기록 열기','primary');const note=x.note||(privateMode?'선택한 원문 주소의 서버 인증을 거칩니다. 본문과 첨부는 이 공개 홈에 포함하지 않습니다.':'기존 상세 본문·이미지·미디어 페이지를 그대로 엽니다.');return `<article class="card chat ${mode}" data-search="${esc(x.label)}"><span class="badge ${mode}">${privateMode?'🔒 비공개':'공개'}</span><h3>${esc(x.label)}</h3><p class="muted">${esc(note)}</p>${action||'<span class="disabled">웹 배포 연결 전</span>'}</article>`}).join('');return `<section id="${mode}"><h2>${esc(title)} <span class="count">${items.length}개</span></h2>${rows?`<div class="grid">${rows}</div>`:`<p class="empty">등록된 ${privateMode?'비공개':'공개'} 채팅이 없습니다.</p>`}</section>`}
function status(p){return `<details><summary>기존 배포·미디어 점검 상태</summary><p>${esc(p.mediaStatus||'미확인')}</p><p>${esc(p.deploymentNote||'운영 배포 상태 확인 전')}</p></details>`}
function project(p){const r=lists(p);document.title=p.title+' · 프로젝트 홈';document.getElementById('title').textContent=p.title;document.getElementById('lead').textContent=p.description||'공개·비공개 채팅 정리 목록';document.getElementById('back').hidden=false;const missing=p.publicRepoUrl&&p.repoStatus!=='missing'?'':'<p class="muted">프로젝트별 공개 저장소는 미연결 상태입니다. 이 공개 안내 홈은 softm.github.io 저장소에서 제공합니다.</p>';return `<nav class="tabs" aria-label="채팅 목록"><a class="button" href="#public">공개 목록 ${r.public.length}</a><a class="button" href="#private">비공개 목록 ${r.private.length}</a></nav><div class="actions repo">${repoLinks(p)}</div>${missing}<p class="note">홈과 채팅 목록은 공개입니다. 비공개 채팅은 클릭한 원문 주소에서 비밀번호 등 해당 서버의 인증을 거친 뒤 열립니다. Vercel 계정 선택 인증의 활성화 여부는 별도 확인이 필요합니다.</p><div class="actions">${button(p.publicUrl,'기존 공개 서비스·기록 홈')}</div><div class="toolbar"><label for="search">채팅 제목 검색</label><input id="search" type="search" placeholder="채팅 제목으로 찾기"></div>${records('공개 채팅·자료 목록',r.public,false)}${records('비공개 채팅·자료 목록',r.private,true)}${status(p)}`}
function directory(projects){document.getElementById('title').textContent='전체 프로젝트';document.getElementById('lead').textContent='프로젝트 홈 → 공개·비공개 채팅 목록 → 선택한 원문';return `<div class="stats"><span class="badge">전체 ${projects.length}개 프로젝트</span><span class="badge">프로젝트 홈은 공개 GitHub Pages</span></div><p class="note">프로젝트명이나 ‘프로젝트 홈’ 버튼을 누르면 로그인 없이 해당 프로젝트의 채팅 목록이 열립니다. 비공개 본문과 미디어는 기존 인증된 사이트에서만 제공합니다.</p><div class="toolbar"><label for="search">프로젝트 검색</label><input id="search" type="search" placeholder="프로젝트명 또는 분야"></div><div class="grid">${projects.map(p=>{const h=homeUrl(p),r=lists(p);return `<article class="card" data-search="${esc(p.title+' '+(p.category||''))}"><span class="badge">${esc(p.category)}</span><h2><a href="${esc(h)}">${esc(p.title)}</a></h2><p>${esc(p.description)}</p><p class="muted">채팅·자료 목록: 공개 ${r.public.length} · 비공개 ${r.private.length}</p><div class="actions">${button(h,'프로젝트 홈 · 채팅 목록','primary')}</div><div class="actions repo">${repoLinks(p)}</div>${status(p)}</article>`}).join('')}</div>`}
async function run(){const area=document.getElementById('app');try{const response=await fetch(BASE+'projects.json?v='+VERSION,{cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);const data=await response.json();if(!Array.isArray(data.projects))throw new Error('프로젝트 목록 형식 오류');const all=data.projects.slice().sort((a,b)=>(a.order||0)-(b.order||0));const slug=location.pathname.replace(/^\/projects\//,'').split('/')[0];const folder=slug==='index.html'?'':slug;const id=document.body.dataset.project||(folder?all.find(p=>new URL(homeUrl(p)).pathname==='/projects/'+folder+'/')?.repo:null);if(folder&&!id)throw new Error('프로젝트 홈 경로를 찾을 수 없습니다.');if(id){const p=all.find(p=>p.repo===id);if(!p)throw new Error('등록된 프로젝트를 찾을 수 없습니다.');area.innerHTML=project(p)}else area.innerHTML=directory(all);const q=document.getElementById('search');q?.addEventListener('input',()=>{const v=q.value.trim().toLocaleLowerCase();document.querySelectorAll('[data-search]').forEach(el=>el.hidden=!el.dataset.search.toLocaleLowerCase().includes(v))});document.documentElement.dataset.rendered=VERSION}catch(e){area.innerHTML=`<p class="empty">목록을 불러오지 못했습니다. ${esc(e.message)}</p>${button('https://github.com/softm/softm.github.io/blob/main/projects/projects.json','원본 목록 확인')}`}}
if(typeof module!=='undefined'&&module.exports){module.exports={homeUrl,lists,safe,unique};return}
run();
})();
