name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: git clone https://github.com/${{ github.repository }}.git

      - name: Install Ruby
        run: |
          sudo apt-get update
          sudo apt-get install ruby-full
          ruby -v

      - name: Set up GEM_HOME
        run: |
          echo "export GEM_HOME=$HOME/.gem" >> $GITHUB_ENV
          echo "export GEM_PATH=$HOME/.gem" >> $GITHUB_ENV
          mkdir -p $HOME/.gem

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: bundle install

      - name: Run Tests
        run: bundle exec rspec
