name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: git clone https://github.com/${{ github.repository }}.git

      - name: Install Ruby
        run: |
          sudo apt-get update
          sudo apt-get install ruby-full
          ruby -v

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: bundle install

      - name: Run Tests
        run: bundle exec rspec
